//! #22 Deep-Q next-node planner interface with greedy fallback.
use crate::types::{CutEvent, LoopCandidate, PackConstraints};
#[derive(Clone,Debug)] pub struct TourState<'a>{pub candidates:&'a [LoopCandidate],pub selected:&'a [usize],pub visited:&'a [bool],pub current:Option<usize>,pub fiber_on:bool,pub constraints:&'a PackConstraints}
pub trait NextNodePolicy{fn next_node(&self,state:&TourState<'_>)->Option<usize>;fn name(&self)->&str;}
pub struct GreedyHeuristicPolicy;
fn centroid(p:&[[f64;2]])->[f64;2]{if p.is_empty(){[0.,0.]}else{let n=p.len() as f64;[p.iter().map(|x|x[0]).sum::<f64>()/n,p.iter().map(|x|x[1]).sum::<f64>()/n]}}
fn dist(a:[f64;2],b:[f64;2])->f64{((a[0]-b[0]).powi(2)+(a[1]-b[1]).powi(2)).sqrt()}
impl NextNodePolicy for GreedyHeuristicPolicy{fn name(&self)->&str{"greedy-heuristic"}fn next_node(&self,s:&TourState<'_>)->Option<usize>{if s.current.is_none(){return s.selected.iter().enumerate().filter(|(i,_)|!s.visited[*i]).max_by(|(_,a),(_,b)|s.candidates[**a].weight.partial_cmp(&s.candidates[**b].weight).unwrap_or(std::cmp::Ordering::Equal)).map(|(i,_)|i)}let cur=centroid(&s.candidates[s.selected[s.current.unwrap()]].points);s.selected.iter().enumerate().filter(|(i,_)|!s.visited[*i]).min_by(|(_,a),(_,b)|dist(cur,centroid(&s.candidates[**a].points)).partial_cmp(&dist(cur,centroid(&s.candidates[**b].points))).unwrap_or(std::cmp::Ordering::Equal)).map(|(i,_)|i)}}}
pub struct DeepQPolicy{weights_path:Option<String>,fallback:GreedyHeuristicPolicy}
impl DeepQPolicy{pub fn new(p:Option<&str>)->Self{Self{weights_path:p.map(str::to_string),fallback:GreedyHeuristicPolicy}}pub fn weights_loaded(&self)->bool{false}pub fn weights_path(&self)->Option<&str>{self.weights_path.as_deref()}}
impl NextNodePolicy for DeepQPolicy{fn name(&self)->&str{"deepq-greedy-fallback"}fn next_node(&self,s:&TourState<'_>)->Option<usize>{self.fallback.next_node(s)}}
pub fn plan_tour(c:&[LoopCandidate],sel:&[usize],k:&PackConstraints,p:&dyn NextNodePolicy)->(Vec<usize>,Vec<CutEvent>,f64,String,Vec<String>){let mut v=vec![false;sel.len()];let mut o=Vec::new();let mut cuts=Vec::new();let mut cur=None;let mut travel=0.;while o.len()<sel.len(){let s=TourState{candidates:c,selected:sel,visited:&v,current:cur,fiber_on:cur.is_some(),constraints:k};let Some(n)=p.next_node(&s)else{break};if v[n]{break}if let Some(q)=cur{let d=dist(centroid(&c[sel[q]].points),centroid(&c[sel[n]].points));travel+=d;if d>k.min_spacing*4.&&k.allow_cuts{cuts.push(CutEvent{after_tour_index:o.len()-1,kind:"cut+restart".into()});travel+=k.cut_cost+k.restart_cost}}v[n]=true;cur=Some(n);o.push(n)}let status=if o.is_empty(){"infeasible"}else if p.name().contains("fallback"){"policy-fallback"}else{"stub-heuristic"};(o,cuts,travel,status.into(),vec![format!("policy={}",p.name()),"card #22 gap: weights not in corpus".into()])}
