use crate::types::{CutEvent, LoopCandidate, PackConstraints}; use serde::Deserialize; use std::path::Path;
#[derive(Clone,Debug,Deserialize)] pub struct DeepQWeightsFile{pub version:u32,pub state_dim:usize,pub action_dim:usize,pub weights:Vec<f64>}
#[derive(Debug,thiserror::Error)] pub enum WeightsLoadError{#[error("weights path missing")]MissingPath,#[error("io: {0}")]Io(#[from]std::io::Error),#[error("json: {0}")]Json(#[from]serde_json::Error),#[error("unsupported version {0} (expected 1)")]BadVersion(u32),#[error("weights length {got} != state_dim*action_dim ({expect})")]BadLength{got:usize,expect:usize},#[error("state_dim and action_dim must be > 0")]BadDims}
pub fn load_weights_file(path:&Path)->Result<DeepQWeightsFile,WeightsLoadError>{let raw=std::fs::read_to_string(path)?;let w:DeepQWeightsFile=serde_json::from_str(&raw)?;if w.version!=1{return Err(WeightsLoadError::BadVersion(w.version))}if w.state_dim==0||w.action_dim==0{return Err(WeightsLoadError::BadDims)}let expect=w.state_dim.saturating_mul(w.action_dim);if w.weights.len()!=expect{return Err(WeightsLoadError::BadLength{got:w.weights.len(),expect})}Ok(w)}
pub struct TourState<'a>{pub candidates:&'a[LoopCandidate],pub selected:&'a[usize],pub visited:&'a[bool],pub current:Option<usize>,pub fiber_on:bool,pub constraints:&'a PackConstraints}
pub trait NextNodePolicy{fn next_node(&self,state:&TourState<'_>)->Option<usize>;fn name(&self)->&str;}
pub struct GreedyHeuristicPolicy;
impl NextNodePolicy for GreedyHeuristicPolicy{fn name(&self)->&str{"greedy-heuristic"}fn next_node(&self,state:&TourState<'_>)->Option<usize>{if state.selected.is_empty(){return None}if state.current.is_none(){let mut best=None;for(si,&ci)in state.selected.iter().enumerate(){if state.visited[si]{continue}let c=&state.candidates[ci];best=match best{None=>Some((si,c.weight,c.id.as_str())),Some((_,w,id))if c.weight>w||(c.weight==w&&c.id.as_str()<id)=>Some((si,c.weight,c.id.as_str())),x=>x}}return best.map(|x|x.0)}fn centroid(p:&[[f64;2]])->[f64;2]{if p.is_empty(){[0.0,0.0]}else{let n=p.len()as f64;[p.iter().map(|x|x[0]).sum::<f64>()/n,p.iter().map(|x|x[1]).sum::<f64>()/n]}}fn dist(a:[f64;2],b:[f64;2])->f64{((a[0]-b[0]).powi(2)+(a[1]-b[1]).powi(2)).sqrt()}let cur=centroid(&state.candidates[state.selected[state.current.unwrap()]].points);let mut best=None;for(si,&ci)in state.selected.iter().enumerate(){if state.visited[si]{continue}let p=centroid(&state.candidates[ci].points);let score=-dist(cur,p);best=match best{None=>Some((si,score)),Some((_,s))if score>s=>Some((si,score)),x=>x}}best.map(|x|x.0)}}
pub struct DeepQPolicy{weights_path:Option<String>,weights:Option<DeepQWeightsFile>,load_note:Option<String>,fallback:GreedyHeuristicPolicy}
impl DeepQPolicy{pub fn new(weights_path:Option<&str>)->Self{let path=weights_path.map(str::to_string);let(weights,load_note)=match path.as_deref(){None=>(None,Some("no weights_path — greedy fallback".into())),Some(p)=>match load_weights_file(Path::new(p)){Ok(w)=>(Some(w),None),Err(e)=>(None,Some(format!("weights unreadable ({e}) — greedy fallback")))}};Self{weights_path:path,weights,load_note,fallback:GreedyHeuristicPolicy}}pub fn weights_loaded(&self)->bool{self.weights.is_some()}pub fn weights_path(&self)->Option<&str>{self.weights_path.as_deref()}pub fn load_note(&self)->Option<&str>{self.load_note.as_deref()}fn encode_state(state:&TourState<'_>,state_dim:usize)->Vec<f64>{let mut f=vec![0.0;state_dim];if state_dim>2{f[2]=if state.fiber_on{1.0}else{0.0}}if state_dim>3{f[3]=state.visited.iter().filter(|&&v|!v).count()as f64}f}fn linear_q_next(&self,state:&TourState<'_>,w:&DeepQWeightsFile)->Option<usize>{let s=Self::encode_state(state,w.state_dim);let mut best=None;for(si,_)in state.selected.iter().enumerate(){if state.visited[si]{continue}let a=si%w.action_dim;let q=(0..w.state_dim).map(|i|s[i]*w.weights[i*w.action_dim+a]).sum();best=match best{None=>Some((si,q)),Some((b,qb))if q>qb||((q-qb).abs()<=f64::EPSILON&&si<b)=>Some((si,q)),x=>x}}best.map(|x|x.0)}}
impl NextNodePolicy for DeepQPolicy{fn name(&self)->&str{if self.weights.is_some(){"deepq-linear"}else{"deepq-greedy-fallback"}}fn next_node(&self,state:&TourState<'_>)->Option<usize>{if let Some(w)=&self.weights{self.linear_q_next(state,w).or_else(||self.fallback.next_node(state))}else{self.fallback.next_node(state)}}}
pub fn plan_tour(candidates:&[LoopCandidate],selected:&[usize],constraints:&PackConstraints,policy:&dyn NextNodePolicy)->(Vec<usize>,Vec<CutEvent>,f64,String,Vec<String>){let mut visited=vec![false;selected.len()];let mut order=Vec::new();let mut cuts=Vec::new();let mut current=None;let mut fiber_on=false;let mut travel=0.0;while order.len()<selected.len(){let state=TourState{candidates,selected,visited:&visited,current,fiber_on,constraints};let Some(next)=policy.next_node(&state)else{break};if visited[next]{break}if let Some(cur)=current{let c=|i|{let p=&candidates[selected[i]].points;let n=p.len()as f64;[p.iter().map(|x|x[0]).sum::<f64>()/n,p.iter().map(|x|x[1]).sum::<f64>()/n]};let a=c(cur);let b=c(next);let d=((a[0]-b[0]).powi(2)+(a[1]-b[1]).powi(2)).sqrt();travel+=d;if d>constraints.min_spacing*4.0&&fiber_on&&constraints.allow_cuts{cuts.push(CutEvent{after_tour_index:order.len().saturating_sub(1),kind:"cut+restart".into()});travel+=constraints.cut_cost+constraints.restart_cost;}}order.push(next);visited[next]=true;current=Some(next);fiber_on=true}let status=if order.is_empty(){"infeasible"}else if policy.name().contains("fallback"){"policy-fallback"}else if policy.name().contains("linear"){"weights-linear"}else if policy.name().contains("greedy"){"stub-heuristic"}else{"feasible"}; (order,cuts,travel,status.into(),vec![format!("policy={}",policy.name()),"card #22 gap: architecture/reward/dataset/weights not in corpus".into()])}
