use crate::types::{LoopCandidate, PackConstraints, PackStrategy};
use std::collections::{HashMap, HashSet};
#[derive(Debug, thiserror::Error)] pub enum PackError { #[error("no candidates")] Empty, #[error("infeasible: {0}")] Infeasible(String) }
pub trait MilpBackend { fn select(&self, candidates: &[LoopCandidate], constraints: &PackConstraints, conflict_pairs: &[(String,String)]) -> Result<Selection, PackError>; }
#[derive(Clone, Debug)] pub struct Selection { pub selected_indices: Vec<usize>, pub unplaced_indices: Vec<usize>, pub strategy_label: String, pub solver_status: String, pub notes: Vec<String> }
pub struct GreedyPackStub;
impl MilpBackend for GreedyPackStub { fn select(&self, candidates: &[LoopCandidate], constraints: &PackConstraints, conflict_pairs: &[(String,String)]) -> Result<Selection,PackError> { greedy_select(candidates,constraints,conflict_pairs) } }
pub fn pack_select(candidates:&[LoopCandidate], constraints:&PackConstraints, conflict_pairs:&[(String,String)], strategy:&PackStrategy)->Result<Selection,PackError>{ let _=strategy; GreedyPackStub.select(candidates,constraints,conflict_pairs) }
fn centroid(p:&[[f64;2]])->[f64;2]{if p.is_empty(){[0.0,0.0]}else{let n=p.len()as f64;[p.iter().map(|x|x[0]).sum::<f64>()/n,p.iter().map(|x|x[1]).sum::<f64>()/n]}}
fn dist(a:[f64;2],b:[f64;2])->f64{((a[0]-b[0]).powi(2)+(a[1]-b[1]).powi(2)).sqrt()}
fn build_conflict_set(c:&[LoopCandidate],x:&PackConstraints,pairs:&[(String,String)])->HashSet<(usize,usize)>{let m:HashMap<&str,usize>=c.iter().enumerate().map(|(i,x)|(x.id.as_str(),i)).collect();let mut s=HashSet::new();for(a,b)in pairs{if let(Some(&i),Some(&j))=(m.get(a.as_str()),m.get(b.as_str())){if i!=j{s.insert(if i<j{(i,j)}else{(j,i)});}}}let cc:Vec<[f64;2]>=c.iter().map(|x|centroid(&x.points)).collect();for i in 0..c.len(){for j in i+1..c.len(){if c[i].layer_id==c[j].layer_id&&dist(cc[i],cc[j])<x.min_spacing{s.insert((i,j));}}}s}
fn bend_ok(c:&LoopCandidate,r:f64)->bool{match c.min_bend_radius{Some(x)=>x+f64::EPSILON>=r,None=>true}}
fn greedy_select(c:&[LoopCandidate],x:&PackConstraints,pairs:&[(String,String)])->Result<Selection,PackError>{if c.is_empty(){return Err(PackError::Empty)}let conflicts=build_conflict_set(c,x,pairs);let mut layers:Vec<u32>=c.iter().map(|x|x.layer_id).collect();layers.sort_unstable();layers.dedup();let mut selected=Vec::new();let mut used=0.0;for layer in layers{let mut order:Vec<usize>=c.iter().enumerate().filter(|(_,x)|x.layer_id==layer).map(|(i,_)|i).collect();order.sort_by(|&a,&b|c[b].weight.partial_cmp(&c[a].weight).unwrap_or(std::cmp::Ordering::Equal).then_with(||c[a].id.cmp(&c[b].id)));for idx in order{if !bend_ok(&c[idx],x.bend_radius)||used+c[idx].length>x.fiber_length_budget+f64::EPSILON{continue}let hit=selected.iter().any(|&s|{let p=if s<idx{(s,idx)}else{(idx,s)};conflicts.contains(&p)});if !hit{selected.push(idx);used+=c[idx].length;}}}selected.sort_unstable();let set:HashSet<usize>=selected.iter().copied().collect();let unplaced=(0..c.len()).filter(|i|!set.contains(i)).collect();Ok(Selection{selected_indices:selected,unplaced_indices:unplaced,strategy_label:"milp-greedy-stub".into(),solver_status:if set.is_empty(){"infeasible".into()}else{"stub-heuristic".into()},notes:vec!["greedy-by-weight layer-wise stand-in — NOT a full MILP".into(),"card #27 gap: solver choice, variable encoding, timing not in corpus".into(),"min_spacing enforced via centroid distance + explicit conflict_pairs".into(),"TODO card #27: interlayer stacking rules not encoded until real MILP".into()]})}
