//! #27 greedy-by-weight stand-in for layer-wise MILP.
use crate::types::{LoopCandidate, PackConstraints, PackStrategy};
use std::collections::{HashMap, HashSet};
#[derive(Debug, thiserror::Error)] pub enum PackError { #[error("no candidates")] Empty, #[error("infeasible: {0}")] Infeasible(String) }
pub trait MilpBackend { fn select(&self, candidates: &[LoopCandidate], constraints: &PackConstraints, conflict_pairs: &[(String,String)]) -> Result<Selection, PackError>; }
#[derive(Clone, Debug)] pub struct Selection { pub selected_indices: Vec<usize>, pub unplaced_indices: Vec<usize>, pub strategy_label: String, pub solver_status: String, pub notes: Vec<String> }
pub struct GreedyPackStub;
impl MilpBackend for GreedyPackStub { fn select(&self,c:&[LoopCandidate],k:&PackConstraints,p:&[(String,String)]) -> Result<Selection,PackError> { greedy_select(c,k,p) } }
pub fn pack_select(c:&[LoopCandidate],k:&PackConstraints,p:&[(String,String)],s:&PackStrategy)->Result<Selection,PackError>{let _=s;GreedyPackStub.select(c,k,p)}
fn cent(p:&[[f64;2]])->[f64;2]{if p.is_empty(){return [0.,0.]} let n=p.len() as f64;[p.iter().map(|x|x[0]).sum::<f64>()/n,p.iter().map(|x|x[1]).sum::<f64>()/n]}
fn d(a:[f64;2],b:[f64;2])->f64{((a[0]-b[0]).powi(2)+(a[1]-b[1]).powi(2)).sqrt()}
fn greedy_select(c:&[LoopCandidate],k:&PackConstraints,p:&[(String,String)])->Result<Selection,PackError>{if c.is_empty(){return Err(PackError::Empty)} let ids:HashMap<&str,usize>=c.iter().enumerate().map(|(i,x)|(x.id.as_str(),i)).collect(); let mut x=HashSet::new(); for(a,b) in p {if let(Some(&i),Some(&j))=(ids.get(a.as_str()),ids.get(b.as_str())){if i!=j{x.insert(if i<j{(i,j)}else{(j,i)});}}} let cents:Vec<_>=c.iter().map(|z|cent(&z.points)).collect(); for i in 0..c.len(){for j in i+1..c.len(){if c[i].layer_id==c[j].layer_id&&d(cents[i],cents[j])<k.min_spacing{x.insert((i,j));}}} let mut layers:Vec<u32>=c.iter().map(|z|z.layer_id).collect();layers.sort_unstable();layers.dedup();let mut sel=Vec::new();let mut used=0.;for l in layers{let mut o:Vec<_>=c.iter().enumerate().filter(|(_,z)|z.layer_id==l).map(|(i,_)|i).collect();o.sort_by(|&a,&b|c[b].weight.partial_cmp(&c[a].weight).unwrap_or(std::cmp::Ordering::Equal).then_with(||c[a].id.cmp(&c[b].id)));for i in o{if c[i].min_bend_radius.map(|r|r+f64::EPSILON>=k.bend_radius).unwrap_or(true)&&used+c[i].length<=k.fiber_length_budget+f64::EPSILON&&!sel.iter().any(|&q|x.contains(&(q.min(i),q.max(i)))){sel.push(i);used+=c[i].length;}}}let set:HashSet<_>=sel.iter().copied().collect();let unplaced=(0..c.len()).filter(|i|!set.contains(i)).collect();Ok(Selection{selected_indices:sel,unplaced_indices:unplaced,strategy_label:"milp-greedy-stub".into(),solver_status:if sel.is_empty(){"infeasible"}else{"stub-heuristic"}.into(),notes:vec!["greedy-by-weight layer-wise stand-in — NOT a full MILP".into()]})}
