//! Principal-stress ingest and dense-grid normalization.
use serde::{Deserialize,Serialize};
use crate::geom::Vec3;
#[derive(Clone,Debug,Serialize,Deserialize)] pub struct PrincipalStressSample{pub position:Vec3,pub principal_direction:Vec3,pub magnitude:f64}
#[derive(Clone,Debug,Serialize,Deserialize)] #[serde(untagged)] pub enum StressIn{PointSamples{samples:Vec<PrincipalStressSample>},DenseGrid{origin:Vec3,spacing:Vec3,dims:[usize;3],magnitudes:Vec<f64>,directions:Vec<Vec3>}}
impl Default for StressIn{fn default()->Self{Self::PointSamples{samples:vec![]}}}
#[derive(Clone,Debug)] pub struct StressGrid{pub origin:Vec3,pub spacing:Vec3,pub dims:[usize;3],pub magnitudes:Vec<f64>,pub directions:Vec<Vec3>}
impl StressGrid{pub fn len(&self)->usize{self.dims[0]*self.dims[1]*self.dims[2]}pub fn index(&self,i:usize,j:usize,k:usize)->usize{i+j*self.dims[0]+k*self.dims[0]*self.dims[1]}pub fn position(&self,i:usize,j:usize,k:usize)->Vec3{[self.origin[0]+i as f64*self.spacing[0],self.origin[1]+j as f64*self.spacing[1],self.origin[2]+k as f64*self.spacing[2]]}pub fn is_empty(&self)->bool{self.len()==0||self.magnitudes.is_empty()}}
pub fn ingest(s:&StressIn)->StressGrid{match s{StressIn::DenseGrid{origin,spacing,dims,magnitudes,directions}=>{let n=dims[0]*dims[1]*dims[2];StressGrid{origin:*origin,spacing:*spacing,dims:*dims,magnitudes:magnitudes.iter().copied().take(n).collect(),directions:directions.iter().copied().take(n).map(crate::geom::normalize).collect()}},StressIn::PointSamples{samples}=>{if samples.is_empty(){return StressGrid{origin:[0.;3],spacing:[1.;3],dims:[0;3],magnitudes:vec![],directions:vec![]}}let origin=samples[0].position;let max=samples.iter().fold(origin,|mut a,s|{for i in 0..3{a[i]=a[i].max(s.position[i])}a});let dims=[4,4,4];let spacing=[((max[0]-origin[0])/3.).max(1e-6),((max[1]-origin[1])/3.).max(1e-6),((max[2]-origin[2])/3.).max(1e-6)];let n=64;let avg=samples.iter().map(|s|s.magnitude).sum::<f64>()/samples.len() as f64;StressGrid{origin,spacing,dims,magnitudes:vec![avg;n],directions:vec![[0.,0.,1.];n]}}}}
